// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ_9SmJa-wbgLWEcx_gpcXiUu471qlW2w',
    appId: '1:268817914041:android:c34824eb5b5e16687fe368',
    messagingSenderId: '268817914041',
    projectId: 'aziza-40e50',
    storageBucket: 'aziza-40e50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA72Oj9elOqZhUdJOuw-3iIvg0X27hveIM',
    appId: '1:268817914041:ios:ab40c3a5fc443b547fe368',
    messagingSenderId: '268817914041',
    projectId: 'aziza-40e50',
    storageBucket: 'aziza-40e50.appspot.com',
    iosBundleId: 'com.example.firebaseapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV4REgssnuUfc5Z_MuZjK2IsqzGEia-J4',
    appId: '1:268817914041:web:bf32f17d84158e1e7fe368',
    messagingSenderId: '268817914041',
    projectId: 'aziza-40e50',
    authDomain: 'aziza-40e50.firebaseapp.com',
    storageBucket: 'aziza-40e50.appspot.com',
    measurementId: 'G-K64EYMJ1G6',
  );
}
